In [22]:
from typing import List

import pandas as pd

**Загрузка данных**

In [23]:
# Создаем DataFrame
df: pd.DataFrame = pd.read_csv("data/data/data.csv", encoding='1251')

# Смотрим, что данные есть
df.head(10)
df.tail(3)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,Авеста,Северная Звезда,1.00,297.74,396.00,0.00,NaN,NaN,48,1,1.00
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,Катрен г.Химки,Кадила Фармасьютикалз Лтд ( CADILA ),1.00,322.06,419.00,0.00,NaN,NaN,48,1,1.00
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],Катрен г.Химки,BELWEDER NORD SIA,1.00,238.62,346.00,34.00,9.00,200010027618.00,48,1,1.00

In [24]:
# По умолчанию pandas отображает только 20 колонок из DataFrame
# Меняем это значение, например, на 40
pd.set_option('display.max_columns', 40)

# И смотрим, что получилось
df.tail(3)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,Авеста,Северная Звезда,1.00,297.74,396.00,0.00,NaN,NaN,48,1,1.00
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,Катрен г.Химки,Кадила Фармасьютикалз Лтд ( CADILA ),1.00,322.06,419.00,0.00,NaN,NaN,48,1,1.00
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],Катрен г.Химки,BELWEDER NORD SIA,1.00,238.62,346.00,34.00,9.00,200010027618.00,48,1,1.00

In [25]:
# Проверим типы данных
df.dtypes

DR_Dat            str
DR_Tim            str
DR_NChk         int64
DR_NDoc         int64
DR_Apt          int64
DR_Kkm          int64
DR_TDoc           str
DR_TPay         int64
DR_CDrugs       int64
DR_NDrugs         str
DR_Suppl          str
DR_Prod           str
DR_Kol        float64
DR_CZak       float64
DR_CRoz       float64
DR_SDisc      float64
DR_CDisc      float64
DR_BCDisc     float64
DR_TabEmpl      int64
DR_VZak         int64
DR_Pos        float64
dtype: object

In [26]:
# Меняем отображение float на число с двумя знаками после запятой
pd.set_option('display.float_format', '{:.2f}'.format)

# И смотрим, что получается
df.tail(3)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,Авеста,Северная Звезда,1.00,297.74,396.00,0.00,NaN,NaN,48,1,1.00
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,Катрен г.Химки,Кадила Фармасьютикалз Лтд ( CADILA ),1.00,322.06,419.00,0.00,NaN,NaN,48,1,1.00
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],Катрен г.Химки,BELWEDER NORD SIA,1.00,238.62,346.00,34.00,9.00,200010027618.00,48,1,1.00

**Манипуляции со столбцами**

In [27]:
# Проверим количество строк и столбцов
print("Строки, поля:", df.shape)

# Либо же можем посмотреть количество 
# элементов = количество строк * количество столбцов
print("Количество элементов:", df.size)

# Посмотрим на индексы в таблицы
print("Информация об индексах:", df.index)

# Посмотрим на поля, которые есть в таблице
print("Поля в таблице:", df.columns)

Строки, поля: (4462, 21)
Количество элементов: 93702
Информация об индексах: RangeIndex(start=0, stop=4462, step=1)
Поля в таблице: Index(['DR_Dat', 'DR_Tim', 'DR_NChk', 'DR_NDoc', 'DR_Apt', 'DR_Kkm', 'DR_TDoc',
       'DR_TPay', 'DR_CDrugs', 'DR_NDrugs', 'DR_Suppl', 'DR_Prod', 'DR_Kol',
       'DR_CZak', 'DR_CRoz', 'DR_SDisc', 'DR_CDisc', 'DR_BCDisc', 'DR_TabEmpl',
       'DR_VZak', 'DR_Pos'],
      dtype='str')

In [28]:
# Оставим только нужные столбцы
# Порядок следования столбцов можно менять

cols: List[str] = [
    'DR_Dat',
    'DR_Tim',
    'DR_NChk',
    'DR_NDoc',
    'DR_Apt',
    'DR_NDrugs',
    'DR_Kol',
    'DR_CZak',
    'DR_CRoz',
    'DR_SDisc',
    'DR_TPay',
    'DR_CDrugs',
    'DR_Suppl',
    'DR_CDisc',
    'DR_BCDisc',
    'DR_TabEmpl',
    'DR_VZak',
    'DR_Pos'
]

df = df[cols]
print(df.shape)
df.head()

(4462, 18)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_NDrugs,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_TPay,DR_CDrugs,DR_Suppl,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925.00,200000000492.00,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9.00,200010010204.00,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9.00,200010010204.00,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9.00,200010010204.00,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925.00,200000000492.00,205,1,1.00

In [29]:
# Переназовем столбцы более удобным образом

df.columns = [
    'dt',
    'c_time',
    'nchk',
    'ndoc',
    'apt',
    'ndrugs',
    'kol',
    'zak',
    'roz',
    'disc',
    'pay_type',
    'drug_id',
    'suppl',
    'disc_id',
    'disc_barcode',
    'empl',
    'vzak',
    'pos'
]

df

,dt,c_time,nchk,ndoc,apt,ndrugs,kol,zak,roz,disc,pay_type,drug_id,suppl,disc_id,disc_barcode,empl,vzak,pos
0,2022-08-11,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925.00,200000000492.00,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9.00,200010010204.00,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9.00,200010010204.00,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9.00,200010010204.00,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925.00,200000000492.00,205,1,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,2022-08-12,21:40:17,5690,18002542,18,КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...,1.00,47.88,75.00,0.00,18,463100,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,NaN,NaN,48,1,1.00
4458,2022-08-12,21:40:59,5691,18002542,18,АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.,1.00,59.51,93.00,0.00,18,112158,Протек,NaN,NaN,48,1,1.00
4459,2022-08-12,21:43:48,5692,18002542,18,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,1.00,297.74,396.00,0.00,18,260990,Авеста,NaN,NaN,48,1,1.00
4460,2022-08-12,21:44:46,5693,18002542,18,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,1.00,322.06,419.00,0.00,18,41512,Катрен г.Химки,NaN,NaN,48,1,1.00
4461,2022-08-12,21:46:08,5694,18002542,18,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],1.00,238.62,346.00,34.00,15,25673,Катрен г.Химки,9.00,200010027618.00,48,1,1.00

**Работа с типами данных**

In [30]:
# Посмотрим типы данных
df.dtypes

dt                  str
c_time              str
nchk              int64
ndoc              int64
apt               int64
ndrugs              str
kol             float64
zak             float64
roz             float64
disc            float64
pay_type          int64
drug_id           int64
suppl               str
disc_id         float64
disc_barcode    float64
empl              int64
vzak              int64
pos             float64
dtype: object

In [31]:
# Попробуем поменять тип disc_barcode

# Сначала проверим еще раз его тип (просто потому что можно)
print("Тип disc_barcode:", df['disc_barcode'].dtype)

# Теперь поменяем его на str
df['disc_barcode'] = df['disc_barcode'].astype('str').replace('\\.0', '', regex=True)
df.head()

Тип disc_barcode: float64

,dt,c_time,nchk,ndoc,apt,ndrugs,kol,zak,roz,disc,pay_type,drug_id,suppl,disc_id,disc_barcode,empl,vzak,pos
0,2022-08-11,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925.00,200000000492,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9.00,200010010204,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9.00,200010010204,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9.00,200010010204,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925.00,200000000492,205,1,1.00

In [32]:
df.dtypes

dt                  str
c_time              str
nchk              int64
ndoc              int64
apt               int64
ndrugs              str
kol             float64
zak             float64
roz             float64
disc            float64
pay_type          int64
drug_id           int64
suppl               str
disc_id         float64
disc_barcode        str
empl              int64
vzak              int64
pos             float64
dtype: object

In [33]:
# Теперь приведем disc_id к int
df['disc_id'] = df['disc_id'].astype('str').replace('\\.0', '', regex=True)
df.head()

,dt,c_time,nchk,ndoc,apt,ndrugs,kol,zak,roz,disc,pay_type,drug_id,suppl,disc_id,disc_barcode,empl,vzak,pos
0,2022-08-11,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925,200000000492,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9,200010010204,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9,200010010204,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9,200010010204,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925,200000000492,205,1,1.00

In [34]:
# Поработаем с датой
df['dt'] = pd.to_datetime(df['dt']).dt.strftime('%d.%m.%Y')
df.head()

,dt,c_time,nchk,ndoc,apt,ndrugs,kol,zak,roz,disc,pay_type,drug_id,suppl,disc_id,disc_barcode,empl,vzak,pos
0,11.08.2022,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925,200000000492,205,1,1.00
1,11.08.2022,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9,200010010204,205,1,1.00
2,11.08.2022,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9,200010010204,205,1,2.00
3,11.08.2022,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9,200010010204,205,1,3.00
4,11.08.2022,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925,200000000492,205,1,1.00

In [35]:
# Заменим целочисленные значения кода операции на текст
df['vzak'].unique()
df['vzak'] = df['vzak'].astype('str').replace('1', 'Обычный').replace('2', 'Интернет')
df.head()

,dt,c_time,nchk,ndoc,apt,ndrugs,kol,zak,roz,disc,pay_type,drug_id,suppl,disc_id,disc_barcode,empl,vzak,pos
0,11.08.2022,10:15:35,2173,2004598,2,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,1.00,41.08,51.00,12.00,18,45399,Катрен г.Химки,925,200000000492,205,Обычный,1.00
1,11.08.2022,10:27:46,2174,2004598,2,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,1.00,18.61,31.00,3.00,15,261519,Катрен г.Химки,9,200010010204,205,Обычный,1.00
2,11.08.2022,10:27:46,2174,2004598,2,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,1.00,132.69,209.00,20.00,15,460864,Катрен г.Химки,9,200010010204,205,Обычный,2.00
3,11.08.2022,10:27:46,2174,2004598,2,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,1.00,133.65,210.00,21.00,15,172823,Катрен г.Химки,9,200010010204,205,Обычный,3.00
4,11.08.2022,10:33:56,2175,2004598,2,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,1.00,709.95,787.00,49.00,18,79056,Катрен г.Химки,925,200000000492,205,Обычный,1.00

**Работа с пропусками**

Заполнение фиксированными значениями

In [36]:
# Проверим, есть ли у нас пропуски хотя бы в одном из столбцов
df.isna().any()

dt              False
c_time          False
nchk            False
ndoc            False
apt             False
ndrugs          False
kol             False
zak             False
roz             False
disc            False
pay_type        False
drug_id         False
suppl           False
disc_id          True
disc_barcode     True
empl            False
vzak            False
pos             False
dtype: bool

In [37]:
df2: pd.DataFrame = pd.read_csv('data/data/data.csv', encoding="1251")
df2.isna().any()

DR_Dat        False
DR_Tim        False
DR_NChk       False
DR_NDoc       False
DR_Apt        False
DR_Kkm        False
DR_TDoc       False
DR_TPay       False
DR_CDrugs     False
DR_NDrugs     False
DR_Suppl      False
DR_Prod       False
DR_Kol        False
DR_CZak       False
DR_CRoz       False
DR_SDisc      False
DR_CDisc       True
DR_BCDisc      True
DR_TabEmpl    False
DR_VZak       False
DR_Pos        False
dtype: bool

In [38]:
df2.fillna(0).isna().any()

DR_Dat        False
DR_Tim        False
DR_NChk       False
DR_NDoc       False
DR_Apt        False
DR_Kkm        False
DR_TDoc       False
DR_TPay       False
DR_CDrugs     False
DR_NDrugs     False
DR_Suppl      False
DR_Prod       False
DR_Kol        False
DR_CZak       False
DR_CRoz       False
DR_SDisc      False
DR_CDisc      False
DR_BCDisc     False
DR_TabEmpl    False
DR_VZak       False
DR_Pos        False
dtype: bool

In [39]:
df2[df2.isna().values.any(axis=1)]

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
15,2022-08-11,11:00:23,2178,2004598,2,22577,Розничная реализация,18,496504,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",Катрен г.Химки,ЛЕККО ФФ ЗАО,1.00,12.94,18.00,0.00,NaN,NaN,205,1,1.00
16,2022-08-11,11:00:23,2178,2004598,2,22577,Розничная реализация,18,496504,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",Катрен г.Химки,ЛЕККО ФФ ЗАО,1.00,12.94,18.00,0.00,NaN,NaN,205,1,2.00
20,2022-08-11,11:31:34,2181,2004598,2,22577,Розничная реализация,18,14120,ЛАКТОФИЛЬТРУМ 500МГ. №60 ТАБ.,Пульс,АВВА РУС ОАО,1.00,408.63,560.00,0.00,NaN,NaN,205,1,1.00
21,2022-08-11,11:31:34,2181,2004598,2,22577,Розничная реализация,18,78641,ФЕСТАЛ №40 ДРАЖЕ,ВИТТА КОМПАНИ ООО,SANOFI,1.00,333.74,458.00,0.00,NaN,NaN,205,1,2.00
22,2022-08-11,11:36:05,2182,2004598,2,22577,Розничная реализация,15,18849,ДОКТОР МОМ №20 ПАСТИЛКИ МАЛИНА,Пульс,Юник Фармасьютикал Лабораториз (Отделение Дж.Б...,1.00,141.55,200.00,0.00,NaN,NaN,205,1,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4456,2022-08-12,21:39:23,5689,18002542,18,9907,Розничная реализация,18,28488,АЛЬБАДЕНТ ОСВЕЖИТЕЛЬ Д/РТА ЛИМОН 35МЛ. СПРЕЙ,Здравсервис,"ХБО при РАН ""Вита""",1.00,62.34,97.00,0.00,NaN,NaN,48,1,1.00
4457,2022-08-12,21:40:17,5690,18002542,18,9907,Розничная реализация,18,463100,КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,47.88,75.00,0.00,NaN,NaN,48,1,1.00
4458,2022-08-12,21:40:59,5691,18002542,18,9907,Розничная реализация,18,112158,АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.,Протек,ИНАТ-ФАРМА,1.00,59.51,93.00,0.00,NaN,NaN,48,1,1.00
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,Авеста,Северная Звезда,1.00,297.74,396.00,0.00,NaN,NaN,48,1,1.00
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,Катрен г.Химки,Кадила Фармасьютикалз Лтд ( CADILA ),1.00,322.06,419.00,0.00,NaN,NaN,48,1,1.00

In [40]:
df3: pd.DataFrame = df2[df2.isna().values.any(axis=1)]
df3.fillna(0).head()

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
15,2022-08-11,11:00:23,2178,2004598,2,22577,Розничная реализация,18,496504,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",Катрен г.Химки,ЛЕККО ФФ ЗАО,1.00,12.94,18.00,0.00,0.00,0.00,205,1,1.00
16,2022-08-11,11:00:23,2178,2004598,2,22577,Розничная реализация,18,496504,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ЛЕККО/",Катрен г.Химки,ЛЕККО ФФ ЗАО,1.00,12.94,18.00,0.00,0.00,0.00,205,1,2.00
20,2022-08-11,11:31:34,2181,2004598,2,22577,Розничная реализация,18,14120,ЛАКТОФИЛЬТРУМ 500МГ. №60 ТАБ.,Пульс,АВВА РУС ОАО,1.00,408.63,560.00,0.00,0.00,0.00,205,1,1.00
21,2022-08-11,11:31:34,2181,2004598,2,22577,Розничная реализация,18,78641,ФЕСТАЛ №40 ДРАЖЕ,ВИТТА КОМПАНИ ООО,SANOFI,1.00,333.74,458.00,0.00,0.00,0.00,205,1,2.00
22,2022-08-11,11:36:05,2182,2004598,2,22577,Розничная реализация,15,18849,ДОКТОР МОМ №20 ПАСТИЛКИ МАЛИНА,Пульс,Юник Фармасьютикал Лабораториз (Отделение Дж.Б...,1.00,141.55,200.00,0.00,0.00,0.00,205,1,1.00

Интерполяция

In [41]:
df2['DR_CDisc'].interpolate(method='linear')

0      925.00
1        9.00
2        9.00
3        9.00
4      925.00
        ...
4457     9.00
4458     9.00
4459     9.00
4460     9.00
4461     9.00
Name: DR_CDisc, Length: 4462, dtype: float64

Удаление пропусков

In [42]:
df2.dropna()

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,DR_Suppl,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,Катрен г.Химки,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.00,41.08,51.00,12.00,925.00,200000000492.00,205,1,1.00
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,Катрен г.Химки,ФЛОРА КАВКАЗА ОАО,1.00,18.61,31.00,3.00,9.00,200010010204.00,205,1,1.00
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,Катрен г.Химки,КОРОЛЕВФАРМ ООО,1.00,132.69,209.00,20.00,9.00,200010010204.00,205,1,2.00
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,Катрен г.Химки,КОРОЛЕВФАРМ ООО,1.00,133.65,210.00,21.00,9.00,200010010204.00,205,1,3.00
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,Катрен г.Химки,Новартис Фарма АГ,1.00,709.95,787.00,49.00,925.00,200000000492.00,205,1,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4416,2022-08-12,20:28:18,5659,18002542,18,9907,Розничная реализация,18,182112,"ИРИФРИН БК 2,5% 0,4МЛ. №15 ГЛ.КАПЛИ ТЮБ./КАП.",Пульс,СЕНТИСС ФАРМА / SENTIS,1.00,716.29,896.00,89.00,939.00,200000000042.00,48,1,1.00
4453,2022-08-12,21:36:07,5687,18002542,18,9907,Розничная реализация,15,72392,"СНУП 0,1% 90МКГ/ДОЗА 15МЛ. НАЗАЛ.СПРЕЙ ФЛ. /ШТ...",Пульс,ФАМАР ХЕЛФ КЕЙР СЕРВИСЕЗ / FAMAR /,1.00,102.45,120.00,6.00,9.00,200010027575.00,48,1,1.00
4454,2022-08-12,21:38:35,5688,18002542,18,9907,Розничная реализация,15,126129,МАКСИКОЛД РИНО АПЕЛЬСИН 15Г. №10 ПОР. Д/Р-РА Д...,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,"Фармстандарт-Томскхимфарм,ОАО",1.00,221.60,295.00,20.00,9.00,200010027575.00,48,1,1.00
4455,2022-08-12,21:38:35,5688,18002542,18,9907,Розничная реализация,15,5852,ЭДАС-306 ПАССАМБРА НЕВРОЗЫ 100МЛ. СИРОП ФЛ.,Катрен г.Химки,ЭДАС,1.00,160.73,221.00,22.00,9.00,200010027575.00,48,1,2.00
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],Катрен г.Химки,BELWEDER NORD SIA,1.00,238.62,346.00,34.00,9.00,200010027618.00,48,1,1.00