# Дополнительные сведения

In [66]:
from typing import Dict, List, Any
import glob

import pandas as pd
from pandas import DataFrame
import numpy as np

## Создание DataFrames:

- Из словаря
- Из списка

In [67]:
# Из словаря
d: Dict = {
    "name": ["Andron", "Liza", "Nikita"], 
    "color": ["green", "red", "blue"]
}

pd.DataFrame(d)

     name  color
0  Andron  green
1    Liza    red
2  Nikita   blue

In [68]:
# Из списка
a: List = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

pd.DataFrame(a)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [69]:
# Если нужно поменять местами столбцы и строки, 
# то можно транспонировать DataFrafe
pd.DataFrame(a).T

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [70]:
# Или можно задать имена колонок в явном виде

pd.DataFrame(a, columns=["A", "B", "C"])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Как сравнить DataFrames

In [71]:
d: Dict = {
    "name": ["Andron", "Liza", "Nikita"], 
    "color": ["green", "red", "blue"]
}

d1 = pd.DataFrame(d)
d2 = pd.DataFrame(d)

In [72]:
d1 == d2

   name  color
0  True   True
1  True   True
2  True   True

In [73]:
d1.equals(d2)

True

# Взять случайные записи

На случай, если нужно взять какую-то случайную выборку из основной совокупности, которая представлена как DataFrame

In [74]:
df: DataFrame = pd.read_csv(
    "data/data/data.csv",
    encoding="1251"
)

df

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,41.08,51.0,12.0,925.0,2.000000e+11,205,1,1.0
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,...,ФЛОРА КАВКАЗА ОАО,1.0,18.61,31.0,3.0,9.0,2.000100e+11,205,1,1.0
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,...,КОРОЛЕВФАРМ ООО,1.0,132.69,209.0,20.0,9.0,2.000100e+11,205,1,2.0
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,...,КОРОЛЕВФАРМ ООО,1.0,133.65,210.0,21.0,9.0,2.000100e+11,205,1,3.0
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,...,Новартис Фарма АГ,1.0,709.95,787.0,49.0,925.0,2.000000e+11,205,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,2022-08-12,21:40:17,5690,18002542,18,9907,Розничная реализация,18,463100,КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,47.88,75.0,0.0,NaN,NaN,48,1,1.0
4458,2022-08-12,21:40:59,5691,18002542,18,9907,Розничная реализация,18,112158,АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.,...,ИНАТ-ФАРМА,1.0,59.51,93.0,0.0,NaN,NaN,48,1,1.0
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,...,Северная Звезда,1.0,297.74,396.0,0.0,NaN,NaN,48,1,1.0
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,...,Кадила Фармасьютикалз Лтд ( CADILA ),1.0,322.06,419.0,0.0,NaN,NaN,48,1,1.0
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],...,BELWEDER NORD SIA,1.0,238.62,346.0,34.0,9.0,2.000100e+11,48,1,1.0

In [75]:
df.sample(3)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
3404,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,490990,СИЛЬВЕР КАПИТАН БАТОНЧИК КОКОС ВАР.СГУЩ.+ЙОГУР...,...,ФАКЕЛ-ДИЗАЙН ООО,2.0,24.48,40.0,0.0,NaN,NaN,123,1,10.0
4158,2022-08-12,10:57:57,5533,18002542,18,9907,Розничная реализация,18,485496,АММИАК 100МГ/МЛ. 100МЛ. №1 Р-Р Д/НАРУЖ./ИНГ. Ф...,...,ТУЛЬСКАЯ ФАРМ. ФАБРИКА,1.0,49.53,77.0,0.0,NaN,NaN,48,1,1.0
1409,2022-08-11,14:02:26,3463,17005029,17,8712,Розничная реализация,15,5093,НАЙЗ 100МГ. №20 ТАБ.,...,ДОКТОР РЕДДИ С ЛАБ / Dr. REDDY's ),1.0,205.48,237.0,16.0,9.0,2.000100e+11,36,1,2.0

## Merge датавфреймов

Это аналог join-а из SQL

In [76]:
abc: DataFrame = pd.DataFrame({
    "name": ["кабачок", "помидор", "огурец"],
    "abc": ["A", "A", "C"]
})

xyz: DataFrame = pd.DataFrame({
    "name_xyz": ["кабачок", "баклажан", "огурец"],
    "xyz": ["X", "Y", "Z"]
})

In [77]:
abc_xyz: DataFrame = abc.merge(xyz, left_on="name", right_on="name_xyz", how="outer")
abc_xyz

      name  abc  name_xyz  xyz
0      NaN  NaN  баклажан    Y
1  кабачок    A   кабачок    X
2   огурец    C    огурец    Z
3  помидор    A       NaN  NaN

In [78]:
abc_xyz["name"] = np.where(abc_xyz["name"].isnull(), abc_xyz["name_xyz"], abc_xyz["name"])
abc_xyz

       name  abc  name_xyz  xyz
0  баклажан  NaN  баклажан    Y
1   кабачок    A   кабачок    X
2    огурец    C    огурец    Z
3   помидор    A       NaN  NaN

In [79]:
abc_xyz.drop("name_xyz", axis=1)

       name  abc  xyz
0  баклажан  NaN    Y
1   кабачок    A    X
2    огурец    C    Z
3   помидор    A  NaN

## Фильтрация столбцов

In [80]:
df.filter(like="ug", axis=1)

      DR_CDrugs                                          DR_NDrugs
0         45399  ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...
1        261519            ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.
2        460864  СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...
3        172823  СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...
4         79056                   ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/
...         ...                                                ...
4457     463100  КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...
4458     112158                           АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.
4459     260990  СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...
4460      41512                         ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.
4461      25673  БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER]

[4462 rows x 2 columns]

## Сохранение датафреймов

In [81]:
df: DataFrame = pd.read_csv(
    "data/data/data.csv",
    encoding="1251"
)

df

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,41.08,51.0,12.0,925.0,2.000000e+11,205,1,1.0
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,...,ФЛОРА КАВКАЗА ОАО,1.0,18.61,31.0,3.0,9.0,2.000100e+11,205,1,1.0
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,...,КОРОЛЕВФАРМ ООО,1.0,132.69,209.0,20.0,9.0,2.000100e+11,205,1,2.0
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,...,КОРОЛЕВФАРМ ООО,1.0,133.65,210.0,21.0,9.0,2.000100e+11,205,1,3.0
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,...,Новартис Фарма АГ,1.0,709.95,787.0,49.0,925.0,2.000000e+11,205,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,2022-08-12,21:40:17,5690,18002542,18,9907,Розничная реализация,18,463100,КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,47.88,75.0,0.0,NaN,NaN,48,1,1.0
4458,2022-08-12,21:40:59,5691,18002542,18,9907,Розничная реализация,18,112158,АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.,...,ИНАТ-ФАРМА,1.0,59.51,93.0,0.0,NaN,NaN,48,1,1.0
4459,2022-08-12,21:43:48,5692,18002542,18,9907,Розничная реализация,18,260990,СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...,...,Северная Звезда,1.0,297.74,396.0,0.0,NaN,NaN,48,1,1.0
4460,2022-08-12,21:44:46,5693,18002542,18,9907,Розничная реализация,18,41512,ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.,...,Кадила Фармасьютикалз Лтд ( CADILA ),1.0,322.06,419.0,0.0,NaN,NaN,48,1,1.0
4461,2022-08-12,21:46:08,5694,18002542,18,9907,Розничная реализация,15,25673,БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER],...,BELWEDER NORD SIA,1.0,238.62,346.0,34.0,9.0,2.000100e+11,48,1,1.0

In [82]:
shops: List[int] = df["DR_Apt"].unique().tolist()
shops

for shop in shops:
    small_df = df[df["DR_Apt"] == shop]
    small_df.to_excel(
        f"data/export/{shop}.xlsx", 
        sheet_name=str(shop), 
        index=False
    )

## Загрузка датафреймов из файлов, объединение

In [83]:
# Прочитает данные из Excel-файла
df_xls: DataFrame = pd.read_excel('data/export/2.xlsx')
df_xls

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,41.08,51.0,12.00,925.0,2.000000e+11,205,1,1
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,...,ФЛОРА КАВКАЗА ОАО,1.0,18.61,31.0,3.00,9.0,2.000100e+11,205,1,1
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,...,КОРОЛЕВФАРМ ООО,1.0,132.69,209.0,20.00,9.0,2.000100e+11,205,1,2
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,...,КОРОЛЕВФАРМ ООО,1.0,133.65,210.0,21.00,9.0,2.000100e+11,205,1,3
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,...,Новартис Фарма АГ,1.0,709.95,787.0,49.00,925.0,2.000000e+11,205,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,28345,АЛЬПИНА СПРИНЦОВКА ПВХ №7Б ТВЕРД.НАКОН. ПЛАСТИ...,...,АЛЬПИНА ПЛАСТ ООО,1.0,112.90,178.0,0.00,NaN,NaN,123,1,1
975,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,490990,СИЛЬВЕР КАПИТАН БАТОНЧИК КОКОС ВАР.СГУЩ.+ЙОГУР...,...,ФАКЕЛ-ДИЗАЙН ООО,2.0,24.48,40.0,0.00,NaN,NaN,123,1,10
976,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,337422,АСКОРБИНКА ВИТАМИН С 25МГ. ДЕТСК. 3Г. №10 ТАБ....,...,ФАРМГРУПП,1.0,8.41,14.0,0.00,NaN,NaN,123,1,2
977,2022-08-12,20:51:41,8490,2004621,2,22569,Розничная реализация,18,4146,ТОТЕМА 10МЛ. №20 Р-Р Д/ПРИЕМА ВНУТРЬ АМП.,...,Иннотера Шузи (INNOTERA),1.0,565.69,775.0,97.21,925.0,2.000000e+11,123,1,3
978,2022-08-12,20:51:41,8490,2004621,2,22569,Розничная реализация,18,14781,ГЕМАТОГЕН РУССКИЙ КОКОС В ГЛАЗУРИ 40Г. ПЛИТКА ...,...,ФАРМ-ПРО,1.0,14.44,24.0,3.01,925.0,2.000000e+11,123,1,2

In [84]:
glob.glob('data/export/*.xlsx')

['data/export/13.xlsx',
 'data/export/15.xlsx',
 'data/export/7.xlsx',
 'data/export/6.xlsx',
 'data/export/11.xlsx',
 'data/export/18.xlsx',
 'data/export/17.xlsx',
 'data/export/2.xlsx']

In [87]:
files: List[str] = glob.glob('data/export/*.xlsx')
dataframes: List[DataFrame] = []

for filename in files:
    part_df = pd.read_excel(filename)
    dataframes.append(part_df)

unioned_pd = pd.concat(dataframes, ignore_index=True)

In [90]:
for i, row in unioned_pd.iterrows():
    print("Номер строки:", i, "Дата:", row['DR_Dat'])
    if i == 10:
        break

Номер строки: 0 Дата: 2022-08-11
Номер строки: 1 Дата: 2022-08-11
Номер строки: 2 Дата: 2022-08-11
Номер строки: 3 Дата: 2022-08-11
Номер строки: 4 Дата: 2022-08-11
Номер строки: 5 Дата: 2022-08-11
Номер строки: 6 Дата: 2022-08-11
Номер строки: 7 Дата: 2022-08-11
Номер строки: 8 Дата: 2022-08-11
Номер строки: 9 Дата: 2022-08-11
Номер строки: 10 Дата: 2022-08-11