In [15]:
from typing import List, Dict, Any

import pandas as pd
from pandas import DataFrame
import numpy as np

# Домашняя работа 3

Загрузите файлы в датафреймы Pandas и назовите их coderun и users. 

Далее создайте новый датафрейм df, который получается в результате:

- Объединения двух датафреймов по полям с пользователем
- Если для каких-то кодранов не найдена пара в таблице users, такие записи нужно все равно оставить в результирующей таблице
- Если есть совпадающие названия столбцов, то у них в результате должны быть суффиксы _run и _user

Далее выполните действия:

- Создайте новый датафрейм df2, который будет хранить информацию о том, сколько дней прошло между последним выполнением кода конкретного юзера и днем его регистрации. Столбец с разницей должен называться diff.
- Округлите diff до ближайшего меньшего числа, кратного 50. Результат должен остаться целым числом.
- Создайте датафрейм df3, в который запишите количество юзеров, сгруппированных по разнице дней.
- Результат отсортируйте по убыванию количества user_id.

In [16]:
# Читаем файлы

coderun: DataFrame = pd.read_csv(
    "data/data/itresume-coderun.csv",
    delimiter=",",
    header=0
)

users: DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv",
    delimiter=";",
    header=1
)

In [17]:
# Смотрим, что там есть
coderun.head()
coderun.agg(["sum", "min"])

,id,created_at,problem_id,user_id,language_id
sum,1552498503,2021-04-07 06:06:20.0002021-03-31 07:10:06.000...,6568782,68194180,122683
min,1,2021-03-27 17:55:11.000,1,1,2

In [18]:
# На всякий случай, посмотрим, порядок следования айдишников пользователей
coderun.sort_values(by="user_id", ascending=True)

          id               created_at  problem_id  user_id  language_id
8          9  2021-04-06 12:14:59.000          24        1            3
22        23  2021-04-18 01:44:20.000           6        1            3
188      189  2021-06-25 18:46:20.358          11        2            3
187      188  2021-06-25 18:46:15.595          11        2            3
186      187  2021-06-25 18:34:41.305          11        2            3
...      ...                      ...         ...      ...          ...
48466  48467  2022-04-20 21:09:43.888         171     2814            3
48463  48464  2022-04-20 21:04:59.490         171     2814            3
48476  48477  2022-04-20 21:14:03.858         171     2814            3
48482  48483  2022-04-20 21:15:19.033         171     2814            3
48430  48431  2022-04-20 20:50:57.715         166     2815            3

[55722 rows x 5 columns]

In [19]:
# Смотрим, что там есть
users.head()

    id       username          date_joined
0  416  nsosabisfsobm  2022-01-02 12:22:43
1   43    NbabnnbTona  2021-07-01 09:11:42
2   50           jbdn  2021-08-04 09:01:56
3  249       Kbaoxsnb  2021-11-27 07:03:35
4   77   bxakbasmo$$$  2021-11-09 14:31:46

In [20]:
# На всякий случай, посмотрим, порядок следования айдишников пользователей
users.sort_values(by="id", ascending=True)

      id       username          date_joined
1     43    NbabnnbTona  2021-07-01 09:11:42
2     50           jbdn  2021-08-04 09:01:56
4     77   bxakbasmo$$$  2021-11-09 14:31:46
5     80       ffbcnbms  2021-11-09 16:22:16
6     81         bdcson  2021-11-10 14:19:29
..   ...            ...                  ...
97  1050     nsosabndsi  2022-02-01 21:02:59
98  1076    SbsdSaobdox  2022-02-02 19:31:21
99  1090           Addb  2022-02-03 13:14:15
7   2633           Eabx  2022-04-06 08:52:40
9   2777  Jonns21241412  2022-04-18 09:33:09

[100 rows x 3 columns]

In [21]:
# Мержим аналогично LEFT JOIN

df: DataFrame = coderun.merge(
    users, 
    left_on="user_id", 
    right_on="id", 
    how="left"
)
df.sort_values(by="user_id")

,id_x,created_at,problem_id,user_id,language_id,id_y,username,date_joined
8,9,2021-04-06 12:14:59.000,24,1,3,NaN,NaN,NaN
22,23,2021-04-18 01:44:20.000,6,1,3,NaN,NaN,NaN
188,189,2021-06-25 18:46:20.358,11,2,3,NaN,NaN,NaN
187,188,2021-06-25 18:46:15.595,11,2,3,NaN,NaN,NaN
186,187,2021-06-25 18:34:41.305,11,2,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
48466,48467,2022-04-20 21:09:43.888,171,2814,3,NaN,NaN,NaN
48463,48464,2022-04-20 21:04:59.490,171,2814,3,NaN,NaN,NaN
48476,48477,2022-04-20 21:14:03.858,171,2814,3,NaN,NaN,NaN
48482,48483,2022-04-20 21:15:19.033,171,2814,3,NaN,NaN,NaN
48430,48431,2022-04-20 20:50:57.715,166,2815,3,NaN,NaN,NaN

In [22]:
df.rename(columns={
    "id_x": "id_run",
    "id_y": "id_user"
})
print(df)

        id_x               created_at  problem_id  user_id  language_id  id_y  \
0          1  2021-04-07 06:06:20.000          13       10            3   NaN
1          2  2021-03-31 07:10:06.000          15       13            3   NaN
2          3  2021-04-04 14:55:26.000           1        6            3   NaN
3          4  2021-03-29 21:24:51.000          26        4            3   NaN
4          5  2021-03-30 11:29:12.000          21       18            3   NaN
...      ...                      ...         ...      ...          ...   ...
55717  55718  2022-05-17 09:00:51.743         101      171            2   NaN
55718  55719  2022-05-17 09:01:04.210         101      171            2   NaN
55719  55720  2022-05-17 09:02:06.203         101      171            2   NaN
55720  55721  2022-05-17 09:03:45.265         102      171            2   NaN
55721  55722  2022-05-17 09:03:57.645         102      171            2   NaN

      username date_joined
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN
...        ...         ...
55717      NaN         NaN
55718      NaN         NaN
55719      NaN         NaN
55720      NaN         NaN
55721      NaN         NaN

[55722 rows x 8 columns]

In [23]:
# сколько дней прошло между последним выполнением кода конкретного юзера и днем его регистрации. Столбец с разницей должен называться diff.

processed: DataFrame = df[["user_id", "created_at", "date_joined"]].sort_values(by="user_id", ascending=True)
processed

       user_id               created_at date_joined
8            1  2021-04-06 12:14:59.000         NaN
22           1  2021-04-18 01:44:20.000         NaN
188          2  2021-06-25 18:46:20.358         NaN
187          2  2021-06-25 18:46:15.595         NaN
186          2  2021-06-25 18:34:41.305         NaN
...        ...                      ...         ...
48466     2814  2022-04-20 21:09:43.888         NaN
48463     2814  2022-04-20 21:04:59.490         NaN
48476     2814  2022-04-20 21:14:03.858         NaN
48482     2814  2022-04-20 21:15:19.033         NaN
48430     2815  2022-04-20 20:50:57.715         NaN

[55722 rows x 3 columns]

In [24]:
# Проверим, что у нас есть реальные даты
processed[~processed["date_joined"].isna()].sort_values(by="user_id", ascending=True)

       user_id               created_at          date_joined
451         43  2021-09-21 14:56:54.741  2021-07-01 09:11:42
321         43  2021-09-20 00:21:23.375  2021-07-01 09:11:42
320         43  2021-09-20 00:16:59.655  2021-07-01 09:11:42
319         43  2021-09-20 00:16:20.639  2021-07-01 09:11:42
318         43  2021-09-20 00:13:16.915  2021-07-01 09:11:42
...        ...                      ...                  ...
47849     2777  2022-04-19 10:51:49.963  2022-04-18 09:33:09
47848     2777  2022-04-19 10:51:40.393  2022-04-18 09:33:09
47847     2777  2022-04-19 10:49:22.419  2022-04-18 09:33:09
47203     2777  2022-04-18 09:42:34.391  2022-04-18 09:33:09
47229     2777  2022-04-18 10:04:50.286  2022-04-18 09:33:09

[11585 rows x 3 columns]

In [25]:
# Приводим данные к типу datetime
processed["created_at"] = pd.to_datetime(processed["created_at"])
processed["date_joined"] = pd.to_datetime(processed["date_joined"])

# Считаем разницу и берем дни
processed["diff"] = (processed["created_at"] - processed["date_joined"]).dt.days
processed

       user_id              created_at date_joined  diff
8            1 2021-04-06 12:14:59.000         NaT   NaN
22           1 2021-04-18 01:44:20.000         NaT   NaN
188          2 2021-06-25 18:46:20.358         NaT   NaN
187          2 2021-06-25 18:46:15.595         NaT   NaN
186          2 2021-06-25 18:34:41.305         NaT   NaN
...        ...                     ...         ...   ...
48466     2814 2022-04-20 21:09:43.888         NaT   NaN
48463     2814 2022-04-20 21:04:59.490         NaT   NaN
48476     2814 2022-04-20 21:14:03.858         NaT   NaN
48482     2814 2022-04-20 21:15:19.033         NaT   NaN
48430     2815 2022-04-20 20:50:57.715         NaT   NaN

[55722 rows x 4 columns]

In [26]:
# Просто проверим, что у нас где-то посчиталась разница
processed[~processed["date_joined"].isna()].sort_values(by="diff", ascending=False)

       user_id              created_at         date_joined   diff
37751       43 2022-03-24 12:31:27.871 2021-07-01 09:11:42  266.0
48633       50 2022-04-21 09:19:56.491 2021-08-04 09:01:56  260.0
48639       50 2022-04-21 09:21:56.419 2021-08-04 09:01:56  260.0
48622       50 2022-04-21 09:12:07.309 2021-08-04 09:01:56  260.0
48627       50 2022-04-21 09:16:21.324 2021-08-04 09:01:56  260.0
...        ...                     ...                 ...    ...
3030       274 2021-11-30 06:03:46.417 2021-11-29 15:02:26    0.0
2997       274 2021-11-29 19:37:19.965 2021-11-29 15:02:26    0.0
2996       274 2021-11-29 19:37:09.125 2021-11-29 15:02:26    0.0
2995       274 2021-11-29 19:36:27.060 2021-11-29 15:02:26    0.0
47229     2777 2022-04-18 10:04:50.286 2022-04-18 09:33:09    0.0

[11585 rows x 4 columns]

In [27]:
processed["diff"] = np.floor(processed["diff"] / 50) * 50
processed[~processed["date_joined"].isna()].sort_values(by="diff", ascending=False)
df2: DataFrame = processed
print(df2)

       user_id              created_at date_joined  diff
8            1 2021-04-06 12:14:59.000         NaT   NaN
22           1 2021-04-18 01:44:20.000         NaT   NaN
188          2 2021-06-25 18:46:20.358         NaT   NaN
187          2 2021-06-25 18:46:15.595         NaT   NaN
186          2 2021-06-25 18:34:41.305         NaT   NaN
...        ...                     ...         ...   ...
48466     2814 2022-04-20 21:09:43.888         NaT   NaN
48463     2814 2022-04-20 21:04:59.490         NaT   NaN
48476     2814 2022-04-20 21:14:03.858         NaT   NaN
48482     2814 2022-04-20 21:15:19.033         NaT   NaN
48430     2815 2022-04-20 20:50:57.715         NaT   NaN

[55722 rows x 4 columns]

In [28]:
df3: DataFrame = (
    df2.groupby("diff", dropna=False)["user_id"]
        .nunique()
        .sort_values(ascending=False)
        .reset_index(name="user_count")
)
print(df3)

    diff  user_count
0    NaN         795
1    0.0          67
2   50.0          22
3  100.0          20
4  150.0           4
5  250.0           2