In [49]:
from typing import List, Dict

import pandas as pd

In [50]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

df2: pd.DataFrame = df.tail(3)
df2

      id     username          date_joined
97  1050   nsosabndsi  2022-02-01 21:02:59
98  1076  SbsdSaobdox  2022-02-02 19:31:21
99  1090         Addb  2022-02-03 13:14:15

In [51]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

params: Dict = {
    'Имена столбцов': df.columns.tolist(),
    'Размер': df.size,
    'Форма': df.shape
}
params

{'Имена столбцов': ['id', 'username', 'date_joined'],
 'Размер': 300,
 'Форма': (100, 3)}

In [52]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

print(df['username'].dtype)
print(df['date_joined'].dtype)

are_types_equal: bool = True if df['username'].dtype == df['date_joined'].dtype else False
are_types_equal

str
str

True

In [53]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

cols: List[str] = [
    "id",
    "date_joined",
    "username"
]
df = df[cols]

col_names: List[str] = [
    "user_id",
    "created_at",
    "login"
]

df.columns = col_names

df

    user_id           created_at          login
0       416  2022-01-02 12:22:43  nsosabisfsobm
1        43  2021-07-01 09:11:42    NbabnnbTona
2        50  2021-08-04 09:01:56           jbdn
3       249  2021-11-27 07:03:35       Kbaoxsnb
4        77  2021-11-09 14:31:46   bxakbasmo$$$
..      ...                  ...            ...
95      946  2022-01-29 18:04:23     Mbbn$xb$eo
96      947  2022-01-29 18:31:26            NaN
97     1050  2022-02-01 21:02:59     nsosabndsi
98     1076  2022-02-02 19:31:21    SbsdSaobdox
99     1090  2022-02-03 13:14:15           Addb

[100 rows x 3 columns]

In [54]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

df = df.dropna()
df['username'] = df['username'].astype('str').replace('\\$', '', regex=True)

In [55]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

dates: List = []

dates = list(pd.unique(pd.to_datetime(df2['date_joined']).dt.strftime('%Y-%m-%d')))
dates

['2022-02-01', '2022-02-02', '2022-02-03']

In [57]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

registrations_by_weekday: Dict = {}

df2 = df.copy()

df2['date_joined'] = pd.to_datetime(df2['date_joined'])
df2['date_joined'] = df2['date_joined'].dt.day_name()

registrations_by_weekday: Dict = (
    df2.groupby('date_joined')['id']
        .count()
        .sort_values(ascending=False)
        .to_dict()
)

print(registrations_by_weekday)
print(df)

{'Wednesday': 19, 'Monday': 18, 'Saturday': 16, 'Thursday': 15, 'Tuesday': 12, 'Sunday': 11, 'Friday': 9}
      id       username          date_joined
0    416  nsosabisfsobm  2022-01-02 12:22:43
1     43    NbabnnbTona  2021-07-01 09:11:42
2     50           jbdn  2021-08-04 09:01:56
3    249       Kbaoxsnb  2021-11-27 07:03:35
4     77   bxakbasmo$$$  2021-11-09 14:31:46
..   ...            ...                  ...
95   946     Mbbn$xb$eo  2022-01-29 18:04:23
96   947            NaN  2022-01-29 18:31:26
97  1050     nsosabndsi  2022-02-01 21:02:59
98  1076    SbsdSaobdox  2022-02-02 19:31:21
99  1090           Addb  2022-02-03 13:14:15

[100 rows x 3 columns]