# Homework 2

In [56]:
from typing import List, Dict, Any

import pandas as pd

## Задание

Загрузите файл в датафрейм Pandas (с именем df).

1. Создайте столбец weekday, в котором будет храниться день недели в русском варианте (Понедельник, Вторник, ...)

2. Создайте столбец date, в котором будет храниться дата регистрации пользователя (без времени)

3. Создайте датафрейм res, который получится в результате группировки исходного датафрейма по дням недели и расчета:

   - Количества регистраций в этот день недели
   - Количества уникальных дат, в которые были регистрации для этого дня недели

   Важно: Столбец с днями недели должен быть не в индексе, а просто столбцом датафрейма.

In [57]:
df: pd.DataFrame = pd.read_csv(
    "data/data/itresume-users-pandas.csv", 
    delimiter=";",
    header=1
)

df.head()

    id       username          date_joined
0  416  nsosabisfsobm  2022-01-02 12:22:43
1   43    NbabnnbTona  2021-07-01 09:11:42
2   50           jbdn  2021-08-04 09:01:56
3  249       Kbaoxsnb  2021-11-27 07:03:35
4   77   bxakbasmo$$$  2021-11-09 14:31:46

In [ ]:
# Создаем новой поле с локализованным днем недели

weekday_map: Dict[str, str] = {
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница",
    "Saturday": "Суббота",
    "Sunday": "Воскресенье",
}

df["weekday"] = pd.to_datetime(df["date_joined"]).dt.day_name().map(weekday_map)

df.head()

    id       username          date_joined      weekday
0  416  nsosabisfsobm  2022-01-02 12:22:43  Воскресенье
1   43    NbabnnbTona  2021-07-01 09:11:42      Четверг
2   50           jbdn  2021-08-04 09:01:56        Среда
3  249       Kbaoxsnb  2021-11-27 07:03:35      Суббота
4   77   bxakbasmo$$$  2021-11-09 14:31:46      Вторник

In [59]:
# Создаем новое поле с датой
df["date"] = pd.to_datetime(df["date_joined"]).dt.strftime("%Y-%m-%d")

df.head()

    id       username          date_joined      weekday        date
0  416  nsosabisfsobm  2022-01-02 12:22:43  Воскресенье  2022-01-02
1   43    NbabnnbTona  2021-07-01 09:11:42      Четверг  2021-07-01
2   50           jbdn  2021-08-04 09:01:56        Среда  2021-08-04
3  249       Kbaoxsnb  2021-11-27 07:03:35      Суббота  2021-11-27
4   77   bxakbasmo$$$  2021-11-09 14:31:46      Вторник  2021-11-09

In [60]:
res_one: pd.DataFrame = df.groupby(["weekday", "date"]).count()
res_one

                        id  username  date_joined
weekday     date
Воскресенье 2021-11-28   3         3            3
            2021-12-05   1         1            1
            2021-12-26   1         1            1
            2022-01-02   1         1            1
            2022-01-09   2         2            2
            2022-01-16   3         3            3
Вторник     2021-11-09   2         2            2
            2021-11-30   4         4            4
            2021-12-28   1         1            1
            2022-01-04   1         1            1
            2022-01-18   2         2            2
            2022-01-25   1         1            1
            2022-02-01   1         1            1
Понедельник 2021-11-29   8         8            8
            2021-12-06   2         2            2
            2021-12-20   4         3            4
            2022-01-17   2         2            2
            2022-01-24   1         1            1
            2022-04-18   1         1            1
Пятница     2021-11-19   1         1            1
            2021-11-26   2         2            2
            2021-12-03   1         1            1
            2021-12-17   3         3            3
            2021-12-24   1         1            1
            2022-01-21   1         1            1
Среда       2021-08-04   1         1            1
            2021-11-10   1         1            1
            2021-11-24   9         9            9
            2021-12-01   1         1            1
            2021-12-08   1         1            1
            2021-12-22   1         1            1
            2021-12-29   1         1            1
            2022-01-05   1         1            1
            2022-01-26   1         1            1
            2022-02-02   1         1            1
            2022-04-06   1         1            1
Суббота     2021-11-27   4         4            4
            2021-12-04   1         1            1
            2021-12-11   1         1            1
            2021-12-18   4         4            4
            2022-01-01   1         1            1
            2022-01-08   2         2            2
            2022-01-22   1         1            1
            2022-01-29   2         1            2
Четверг     2021-07-01   1         1            1
            2021-11-25   6         6            6
            2021-12-02   3         3            3
            2021-12-30   2         2            2
            2022-01-13   1         1            1
            2022-01-27   1         1            1
            2022-02-03   1         1            1

In [61]:
res: pd.DataFrame = df.groupby(["weekday"]).agg({
    "date": "nunique",
    "id": "count"
}).reset_index()
res

       weekday  date  id
0  Воскресенье     6  11
1      Вторник     7  12
2  Понедельник     6  18
3      Пятница     6   9
4        Среда    11  19
5      Суббота     8  16
6      Четверг     7  15